version: '3.8'
services:
  bot:
    build: .
    command: python ./algalon_bot/bot.py
    environment:
      PYTHONPATH: .
    volumes:
      - ./:/usr/src/app/:cached
    depends_on:
      - "postgres"
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

volumes:
  db-data: