robot:
    gap: 10.0
    gap_ignore: 5.0
exchange:
    client_id: oUJiardE
    client_secret: erxsqCtEKczqtTXHpMDR106I-Gs60wyPtPQt8LHk9Jw
    api_link: wss://test.deribit.com/ws/api/v2
    instrument_name: BTC-PERPETUAL
    amount: 10
    